logging:
  level: 10

udp:
  port: 1700

mqtt:
  enabled: False
  server: localhost
  port: 1883
  username:
  password:
  topic: gts/example

file:
  enabled: False
  uplinks: /app/data/uplinks.log
  joinreqs: /app/data/joinreqs.log

web:
  enabled: True
  port: 8888

general:
  buffer: 500

client:
  buttons:
    mode: True
    screen: False
    fullscreen: False
  