version: '2.0'

services:

  #mosquitto:
  #  image: eclipse-mosquitto:1.6
  #  container_name: mosquitto
  #  restart: unless-stopped
  #  ports:
  #    - 1883:1883

  udp-packet-forwarder:
    image: rakwireless/udp-packet-forwarder:latest
    container_name: udp-packet-forwarder
    restart: unless-stopped
    privileged: true
    environment:
      MODEL: RAK7271
      SERVER_HOST: lorawan-packet-sniffer
      SERVER_PORT: 1700
  
  lorawan-packet-sniffer:
    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lorawan-packet-sniffer
    restart: unless-stopped
    privileged: true
    ports:
      - 1700:1700
      - 8888:8888

    # Either mount the configuration file
    #volumes:
    #  - ./config.yml:/app/config.yml

    # Or use environment variables to configure the service
    environment:
      
      LOGGING_LEVEL: 10
      
      GENERAL_BUFFER: 500
      
      UDP_PORT: 1700
      
      MQTT_ENABLED: False
      MQTT_SERVER: mosquitto
      MQTT_PORT: 1883
      MQTT_USERNAME: 
      MQTT_PASSWORD:
      MQTT_TOPIC: gts/message
      
      WEB_ENABLED: True
      WEB_PORT: 8888
